language: rust
sudo: required
os: linux
addons:
  apt:
    packages:
      - libssl-dev
      - python3
      - python3-pip
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
  - pip3 install --user travis -r requirements-test.txt
script:
  - cargo clean
  - cargo build 
  - cargo test
  - cargo fmt --all -- --check
after_success: | 
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install -f cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
